### ISSUE TITLE
靓仔你这个项目牛逼啊

### ISSUE THREAD

**Issue by zhaotianff** [zmjack/NWin32#2]
所有的签名都是自己打的吗，还是爬虫过来的。

**Comment by zmjack** [comment]
Interop Assistant 生成的，改了一些签名。

有些签名还不是很准确，本来打算用新规则来生成签名，还没时间做。

我没有做过任何推广，你是怎么找到这里的？

**Comment by zhaotianff** [comment]
我一般都是根据官方文档，直接手写转过来的，我看你这个挺齐全的，所以觉得很牛逼。github日推了你Chinese那个项目，我就看到了这个项目。
